modLoader="kotlinforforge"
loaderVersion="[4,)"

issueTrackerURL="https://github.com/SirEdvin/Geodes/issues"
logoFile="pack.png"

license="MIT"

[[mods]]
modId="geodes"
version="${file.jarVersion}"
displayName="Geodes"
displayURL="https://github.com/SirEdvin/Geodes"

credits=""
authors=""
description='''
'''

[[dependencies.geodes]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},48)"
ordering="NONE"
side="BOTH"

[[dependencies.geodes]]
modId="peripheralium"
mandatory=true
versionRange="[${peripheraliumVersion},)"
ordering="NONE"
side="BOTH"